version: '3.8'

services:
  app:
    image: alsqja2626/pan-ttegi:latest
    container_name: app-container
    #    env_file:
    #      - /home/ubuntu/.env
    environment:
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - pan-net

  db:
    image: mysql:latest
    container_name: mysql-container
    #    env_file:
    #      - /home/ubuntu/.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: pan_ttegi
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "--silent" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - pan-net

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pan-net

networks:
  pan-net:
    driver: bridge