version: '3.8'

services:
  app:
    image: alsqja2626/pan-ttegi:latest
    container_name: app-container
    restart: always
    environment:
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      #      - db
      - redis
    networks:
      - pan-net

  #    db:
  #      image: mysql:latest
  #      container_name: mysql-container
  #      environment:
  #        MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
  #        MYSQL_DATABASE: pan_ttegi
  #      ports:
  #        - "3306:3306"
  #      networks:
  #        - pan-net

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - pan-net

networks:
  pan-net:
    driver: bridge