name: CI Workflow for Gradle

on:
  push:
    branches:
      - '**' # 모든 브랜치에서 push 이벤트 감지
  pull_request:
    branches:
      - develop
      - main # PR이 develop 또는 main으로 병합될 때 실행

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up environment variables
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run: |
          echo "Environment variables set for testing"

      - name: Run Gradle Tests
        run: |
          ./gradlew clean test
